#!/bin/bash
# Copyright (c) 2000,2004 Matthias S. Benkmann <article AT winterdrache DOT de>
# You may do everything with this code except misrepresent its origin.
# PROVIDED `AS IS' WITH ABSOLUTELY NO WARRANTY OF ANY KIND!

if [ $# -lt 1 ]; then
  echo 1>&2
  echo 1>&2 'USAGE: install_package <name>'
  echo 1>&2
  echo 1>&2 'Creates a new package user called <name> with primary group <name> (username and groupname are the same).'
  echo 1>&2 'If the user account has been created successfully, `su - <name>'"'"' will be'
  echo 1>&2 'executed so that you can start working with the new account right away.'
  echo 1>&2
  echo 1>&2 'This script leaves the actual creation of the new account to the'
  echo 1>&2 'add_package_user script. Check out its documentation for details.'
  echo 1>&2
  exit 1
fi

export PATH="/usr/sbin:/sbin:$PATH"

if [ $UID -ne 0 ]; then
  echo "You may have to run this script ($0) as root"
fi

XUSER="$1"
DESC="$XUSER"
XGROUP="$XUSER"
add_package_user "$DESC" "$XUSER" 10000 20000 "$XGROUP" 10000 20000 || exit 1
exec su - "$XUSER"
