#!/bin/bash
# Copyright (c) 2000,2004 Matthias S. Benkmann <article AT winterdrache DOT de>
# You may do everything with this code except misrepresent its origin.
# PROVIDED `AS IS' WITH ABSOLUTELY NO WARRANTY OF ANY KIND!

DAISY_CHAIN=""

for p in $(type -ap chgrp) ; do
  if [ ! $p -ef $0 ]; then DAISY_CHAIN=$p ; break ; fi
done

if [ ! -n "$DAISY_CHAIN" ]; then
  echo Cannot find real ${0##*/} command
  exit 1
fi

if [ $UID == 0 ]; then
  exec $DAISY_CHAIN "$@"
fi

# Extension:
# When requested to change group to "install" do either nothing (if the file
# has already that group) or just print a message '**** ' with the command
# and exit with 0
if [ $# == 2 ] ; then
  if [ "$1" == "install" ] ; then
    bgc=`stat -c "%G" "$2"`
    if [ "$1" == "$bgc" ] ; then
      exit 0
    fi
    echo "**** $@"
    exit 0
  fi
fi

if [ "$1" == "tty" ]; then
  echo 1>&2 '***' chgrp "$@"
else
  /usr/lib/pkgusr/exec $DAISY_CHAIN "$@" || exit $?
fi

exit 0
