#! /bin/bash

# This script simulates `/usr/bin/install-info`, which would normally write to
# `/usr/share/info/dir`, but it is written by many install users. Similar problem
# to ld-config.

echo "**** $0 $@"

exit 0
