# Begin /etc/bashrc
# Written for Beyond Linux From Scratch
# by James Robertson <jameswrobertson@earthlink.net>
# updated by Bruce Dubbs <bdubbs@linuxfromscratch.org>

echo "/etc/bashrc" 1>&2

# Make sure that the terminal is set up properly for each shell

if [ -f /etc/profile.d/tinker-term.sh ]; then
  source /etc/profile.d/tinker-term.sh
fi

# System wide aliases and functions.

# System wide environment variables and startup programs should go into
# /etc/profile.  Personal environment variables and startup programs
# should go into ~/.bash_profile.  Personal aliases and functions should
# go into ~/.bashrc

# Provides a colored /bin/ls command.  Used in conjunction with code in
# /etc/profile.

alias cp='cp --sparse=always'

alias ls='ls --time-style=long-iso -B --color=auto'
alias ll='ls -l -B --color=auto'
# Win32-Version
alias dir='ls -bla --color=auto'
alias c='clear'
# Win32-Version
alias cls='clear'
# Calendar: Week starts with Monday
alias cal='cal -m'

alias mroe='more'
alias pdw='pwd'
alias sl='ls --color'

alias du='du -hs'
alias df='df -h'

# Provides prompt for non-login shells, specifically shells started
# in the X environment. [Review the LFS archive thread titled
# PS1 Environment Variable for a great case study behind this script
# addendum.]

#export PS1="[\u@\h \w]\\$ "
export PS1='\u@\h:\w\$ '

# $Id: bash_completion.sh,v 1.2 2006/02/25 01:21:33 ianmacd Exp $

# Check for bash (and that we haven't already been sourced).
[ -z "$BASH_VERSION" -o -n "$BASH_COMPLETION" ] && return

# Check for interactive shell.
if [ -n "$PS1" ]; then
  if [ -r /etc/bash_completion ]; then
    # Source completion code.
    . /etc/bash_completion
  fi
fi

# End /etc/bashrc
